// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_error from "./routes/_error.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $dyana from "./routes/dyana.tsx";
import * as $generate_guid from "./routes/generate-guid.tsx";
import * as $generate_hex from "./routes/generate-hex.tsx";
import * as $generate_processid from "./routes/generate-processid.tsx";
import * as $index from "./routes/index.tsx";
import * as $timespan_explainer from "./routes/timespan-explainer.tsx";
import * as $DyanaWindow from "./islands/DyanaWindow.tsx";
import * as $InOutTextBoxView from "./islands/InOutTextBoxView.tsx";
import * as $OutTextBoxView from "./islands/OutTextBoxView.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_error.tsx": $_error,
    "./routes/_middleware.ts": $_middleware,
    "./routes/dyana.tsx": $dyana,
    "./routes/generate-guid.tsx": $generate_guid,
    "./routes/generate-hex.tsx": $generate_hex,
    "./routes/generate-processid.tsx": $generate_processid,
    "./routes/index.tsx": $index,
    "./routes/timespan-explainer.tsx": $timespan_explainer,
  },
  islands: {
    "./islands/DyanaWindow.tsx": $DyanaWindow,
    "./islands/InOutTextBoxView.tsx": $InOutTextBoxView,
    "./islands/OutTextBoxView.tsx": $OutTextBoxView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
