//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("AppSea.Test")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("AppSea.Test")]
[assembly: AssemblyVersion("1.0.2018.0122")]
[assembly: AssemblyFileVersion("1.0.2018.0122")]
[assembly: AssemblyInformationalVersion("1.0.2018.0122")]
[assembly: AssemblyCopyright("Copyright ©  2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: Guid("c325f8de-e880-4092-ad4a-44098195aced")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

